### ISSUE TITLE
Can't run on own folder

### ISSUE THREAD

**Issue by sacdallago** [hkmztrk/SMILESbasedSimilarityKernels#2]
Hi :)

thanks for this piece of software! I'm having trouble running it (might be related to #1 ). I'm also running on OsX but I'm using my own SMILES.

I run: `java -jar tools/SMILESSim.jar ../data/smiles` and get:

```bash
---------edit------------------
---------../data/smiles------------------
0
1
2
3
... [cropping content for readability]...
1410
1411
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.io.FileNotFoundException: ./simmatrix/edit_../data/smiles_simmat_dc.txt (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at java.io.FileWriter.<init>(FileWriter.java:63)
	at smileskernels.SMILESKernels.writeSimMatrix(SMILESKernels.java:206)
	at smileskernels.SMILESKernels.main(SMILESKernels.java:171)
	... 5 more
```

1. This is very strange, because my data folder and my tools folder lie in the same directory (thus the `..` is somehow incorrect, but it's the only way to make it work).
  An `ls` of where I'm running the thing: 
  ```bash
ls
PROCEDERE.md			libs				simmatrix			train.ipynb
SMILES_for_similarity.ipynb	models				src
create_features.ipynb		predict.ipynb			tests
data				process_data.ipynb		tools
  ```

2. I believe it fails when trying to create the summary files, e.g.: the line `./simmatrix/edit_../data/smiles_simmat_dc.tx`.

3. If I copy the smiles folder over to my my tools dir and run everything from there, aka: `java -jar SMILESSim.jar smiles` or `java -jar SMILESSim.jar smiles\` or `java -jar SMILESSim.jar ./smiles` or `java -jar SMILESSim.jar ./smiles/` or `java -jar SMILESSim.jar ../smiles` or `java -jar SMILESSim.jar ../smiles/` I always get:

```bash
---------edit------------------
---------[./|../|]smiles[/|]------------------
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NullPointerException
	at ioops.readSMILES.readSMILESfromFolder(readSMILES.java:24)
	at smileskernels.SMILESKernels.main(SMILESKernels.java:74)
	... 5 more
```

Would greatly appreciate your help :)

**eidt**: notice how it created the folder `simmatrix` in my root. That wasn't there before running the command, but the content of the folder is empty :)

**Comment by hkmztrk** [comment]
Hello, thanks for your feedback!

Yes, I think for the first problem somehow it fails to create output files, and for the second one it seems it can't read from the smiles folder.
I'll check out to see what's wrong and let you know. Could you please attach a file or two from your smiles folder just in case?

Thanks!

**Comment by hkmztrk** [comment]
Hello again!

So, to create output files, I use folder names which in this case is "../data/smiles". I think the problem was the use of "/" in the file name, so I simply removed them. It worked fine on Linux. Please let me know if the problem still continues.

I tested with your first option, here are my folders:

```
tester
  |-data
     |-smiles
  |-tools
     |-SMILESSimv2.jar
```

So under `tester folder`, I run 

`java -jar tools/SMILESSimv2.jar ./data/smiles`


It should also work like this,

```
tester
  |-data
     |-smiles
     |-SMILESSimv2.jar
```

Under `data folder`,

`java -jar SMILESSimv2.jar smiles`

**Comment by sacdallago** [comment]
@hkmztrk I'm now trying with `SMILESSimv2.jar` and `java -jar tools/SMILESSimv2.jar data/smiles` and the first run has already produced the _edit_ (and I see the file in my directory). So I assume it all works now. I'll update again once the algorithm has produced all results (/close the issue), in the mean time **thank you** for the quick fix.

**Comment by hkmztrk** [comment]
You're welcome! Hope everything's is ok!

**Comment by sacdallago** [comment]
Still running 🙈 :) but all good for now. I hope that by tomorrow it's gonna be done, then comes another update :)

**Comment by sacdallago** [comment]
Yay :confetti_ball: 

```bash
Elapsed time was 97679785 seconds.
```

Thank you :) If I can suggest a new feature it would be that of being able to start jobs (algs) selectively. Other than that, great work

**Comment by hkmztrk** [comment]
@sacdallago glad it worked! :) It's a great suggestion, I'll do that.
Good luck with your work!
